### PR TITLE
Fix the infinite loop when `max_input_length` is bigger than `max-batch-tokens`

### LINKED ISSUE #694: Some inputs hang the whole embedding service on Qwen3-Embedding-0.6B
### System Info

On some inputs (example attached) for Qwen/Qwen3-Embedding-0.6B, the tei server embedding service stops responding.
The HTTP request with the borked input does not get a response and other requests will not be served.

In wireshark I can see that the request is sent, but there is nothing coming back from the server.

### Information

- [x] Docker
- [ ] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

On both cuda and ipex cpu.

```
# docker run --rm --gpus all -p 8000:80 -v /opt/tei_data:/data --pull always ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-latest --model-id Qwen/Qwen3-Embedding-0.6B 
cpu-ipex-latest: Pulling from huggingface/text-embeddings-inference
Digest: sha256:f1c8b121b9b0582b7ae3e4180f2eebcf968aa8c8de3a1965969b61870c6a48a5
Status: Image is up to date for ghcr.io/huggingface/text-embeddings-inference:cpu-ipex-latest
```

and 

```
# docker run --rm --gpus all -p 8000:80 -v /opt/tei_data:/data --pull always ghcr.io/huggingface/text-embeddings-inference:1.8 --model-id Qwen/Qwen3-Embedding-0.6B
1.8: Pulling from huggingface/text-embeddings-inference
Digest: sha256:8aeb97215f29e0ed48647384af89661c36cee04120c2d4e86b5a3aead47611fa
Status: Image is up to date for ghcr.io/huggingface/text-embeddings-inference:1.8
```

`curl -vvvv -H "Content-Type: application/json" -d @tei_qwen_embed_0.6b_broken_input.txt http://inference:8000/embed`

[tei_qwen_embed_0.6b_broken_input.txt](https://github.com/user-attachments/files/21702606/tei_qwen_embed_0.6b_broken_input.txt)

### Expected behavior

The HTTP request should not hang and it also should not block other embed requests.

### LINKED ISSUE #723: Infinite Loop When max-batch-tokens < model max_input_length
### System Info

cargo 1.85.1 (d73d2caf9 2024-12-31)

```
{
  "model_id": "Qwen/Qwen3-Embedding-0.6B",
  "model_sha": null,
  "model_dtype": "float32",
  "model_type": {
    "embedding": {
      "pooling": "last_token"
    }
  },
  "max_concurrent_requests": 512,
  "max_input_length": 32768,
  "max_batch_tokens": 1000,
  "max_batch_requests": 4,
  "max_client_batch_size": 32,
  "auto_truncate": false,
  "tokenization_workers": 32,
  "version": "1.8.2",
  "sha": "ff3969a9e55405dda42b6dd167bd0c5c6900c2b0",
  "docker_label": null
}
```

Linux hostname 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Hardware: cpu only run

### Information

- [ ] Docker
- [x] The CLI directly

### Tasks

- [x] An officially supported command
- [ ] My own modifications

### Reproduction

1. `cargo run --release --features candle,ort,http --no-default-features -- --model-id Qwen/Qwen3-Embedding-0.6B --max-batch-tokens 1000`
2. `curl -vvvv -H "Content-Type: application/json" -d @tei_qwen_embed_0.6b_broken_input.json http://localhost:3000/embed`

[tei_qwen_embed_0.6b_broken_input.json](https://github.com/user-attachments/files/22400450/tei_qwen_embed_0.6b_broken_input.json)

 - from [issue 694](https://github.com/huggingface/text-embeddings-inference/issues/694)

3. Request will never end, infer actually not started (0% of cpu usage)

Source code found:

https://github.com/huggingface/text-embeddings-inference/blob/ff3969a9e55405dda42b6dd167bd0c5c6900c2b0/core/src/queue.rs#L155

### Expected behavior

Depends on configuration. If Auto truncate is set - truncate to `Min(max_batch_tokens, max_input_tokens)`. If not - reply with and Error.

### PR DESCRIPTION
**Pull request by kozistr**
# What does this PR do?

Fixes #723
Fixes #694

## Changes

* Raise an error when `max_input_length` is bigger than `max_batch_tokens` and `auto-truncate` is disabled.
* Reduce `max_input_length` to `max_batch_tokens` when `auto-truncate` is enabled.

Feel free to let me know whether this approach would be proper or not 🤗

## Log

```
./target/release/text-embeddings-router --model-id ../Qwen3-Embedding-0.6B/ --pooling last-token --port 8080 --dtype float32 --max-batch-tokens 1024
2025-09-20T10:05:20.198290Z  INFO text_embeddings_router: router/src/main.rs:203: Args { model_id: "../Qwe**-*********-0.6B/", revision: None, tokenization_workers: None, dtype: Some(Float32), pooling: Some(LastToken), max_concurrent_requests: 512, max_batch_tokens: 1024, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, default_prompt_name: None, default_prompt: None, dense_path: None, hf_api_token: None, hf_token: None, hostname: "0.0.0.0", port: 8080, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: None, payload_limit: 2000000, api_key: None, json_output: false, disable_spans: false, otlp_endpoint: None, otlp_service_name: "text-embeddings-inference.server", prometheus_port: 9000, cors_allow_origin: None }
2025-09-20T10:05:20.516435Z  WARN text_embeddings_router: router/src/lib.rs:191: Could not find a Sentence Transformers config
Error: `max_input_length` must be smaller than `max_batch_tokens` when `auto_truncate` is disabled (32768 > 1024)
```

```
./target/release/text-embeddings-router --model-id ../Qwen3-Embedding-0.6B/ --pooling last-token --port 8080 --dtype float32 --max-batch-tokens 1024 --auto-truncate
2025-09-20T09:59:09.902213Z  INFO text_embeddings_router: router/src/main.rs:203: Args { model_id: "../Qwe**-*********-0.6B/", revision: None, tokenization_workers: None, dtype: Some(Float32), pooling: Some(LastToken), max_concurrent_requests: 512, max_batch_tokens: 1024, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: true, default_prompt_name: None, default_prompt: None, dense_path: None, hf_api_token: None, hf_token: None, hostname: "0.0.0.0", port: 8080, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: None, payload_limit: 2000000, api_key: None, json_output: false, disable_spans: false, otlp_endpoint: None, otlp_service_name: "text-embeddings-inference.server", prometheus_port: 9000, cors_allow_origin: None }
2025-09-20T09:59:10.231469Z  WARN text_embeddings_router: router/src/lib.rs:191: Could not find a Sentence Transformers config
2025-09-20T09:59:10.231513Z  WARN text_embeddings_router: router/src/lib.rs:205: Reduce `max_input_length` to `max_batch_tokens` (from 32768 to 1024)
2025-09-20T09:59:10.231517Z  INFO text_embeddings_router: router/src/lib.rs:215: Maximum number of tokens per request: 1024
2025-09-20T09:59:10.231673Z  INFO text_embeddings_core::tokenization: core/src/tokenization.rs:38: Starting 8 tokenization workers
2025-09-20T09:59:10.534633Z  INFO text_embeddings_router: router/src/lib.rs:263: Starting model backend
2025-09-20T09:59:10.539197Z  INFO text_embeddings_backend_candle: backends/candle/src/lib.rs:305: Starting Qwen3 model on Cpu
2025-09-20T09:59:13.086429Z  INFO text_embeddings_router: router/src/lib.rs:281: Warming up model
2025-09-20T09:59:25.175351Z  WARN text_embeddings_router: router/src/lib.rs:290: Backend does not support a batch size > 4
2025-09-20T09:59:25.175381Z  WARN text_embeddings_router: router/src/lib.rs:291: forcing `max_batch_requests=4`
2025-09-20T09:59:25.176762Z  INFO text_embeddings_router::http::server: router/src/http/server.rs:1852: Starting HTTP server: 0.0.0.0:8080
2025-09-20T09:59:25.176786Z  INFO text_embeddings_router::http::server: router/src/http/server.rs:1853: Ready
2025-09-20T10:00:00.953783Z  INFO embed{total_time="11.896093678s" tokenization_time="31.117792ms" queue_time="407.883µs" inference_time="11.864449086s"}: text_embeddings_router::http::server: router/src/http/server.rs:733: Success

curl -vvvv -H "Content-Type: application/json" -d @tei_qwen_embed_0.6b_broken_input.json http://localhost:8080/embed
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /embed HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 55126
> 

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< x-compute-type: gpu+optimized
< x-compute-time: 11896
< x-compute-characters: 55060
< x-compute-tokens: 1024
< x-total-time: 11896
< x-tokenization-time: 31
< x-queue-time: 0
< x-inference-time: 11864
< vary: origin, access-control-request-method, access-control-request-headers
< access-control-allow-origin: *
< content-length: 12759
< date: Sat, 20 Sep 2025 10:00:00 GMT
```

## Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/text-embeddings-inference/blob/main/CONTRIBUTING.md)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs).
- [ ] Did you write any new necessary tests? If applicable, did you include or update the `insta` snapshots?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Narsil @alvarobartt

### CODE REVIEW

File: router/src/lib.rs [hunk 1]
```diff
@@ -184,13 +184,34 @@ pub async fn run(
...
             tracing::warn!("Could not find a Sentence Transformers config");
             config.max_position_embeddings - position_offset
         }
     };
+
+    // Raise an error when max_input_length is bigger than max_batch tokens to prevent an infinite loop in the queue
+    let max_input_length = if base_input_length > max_batch_tokens {
+        if !auto_truncate {
+            anyhow::bail!(
+                "`max_input_length` must be smaller than `max_batch_tokens` when `auto_truncate` is disabled ({} > {})",
```
Comment (alvarobartt) [inline router/src/lib.rs]:
```suggestion
                "`--max-batch-tokens` cannot be lower than the model `max_input_length` ({} < {}) when `--auto-truncate` is disabled, add the `--auto-truncate` flag to truncate the input sequences to match the `--max-batch-tokens`.",
```

File: router/src/lib.rs [hunk 2]
```diff
@@ -184,13 +184,34 @@ pub async fn run(
...
+                base_input_length,
+                max_batch_tokens
+            );
+        }
+        tracing::warn!(
+            "Reduce `max_input_length` to `max_batch_tokens` (from {} to {})",
+            base_input_length,
+            max_batch_tokens
+        );
```
Comment (alvarobartt) [inline router/src/lib.rs:210]:
```suggestion
        tracing::warn!(
            "The input sequences will be truncated to {} tokens even if the model `max_input_length` is greater than the provided `--max-batch-tokens` ({} > {}), as `--auto-truncate` is enabled.",
            max_batch_tokens,
            base_input_length,
            max_batch_tokens
        );
```

File: router/src/lib.rs (hunk 1 above)
Comment (alvarobartt) [reply router/src/lib.rs]: I've tried to word that in a way so that there's an actionable item for the user given that there's no built-in way to modify the `max_input_length` of the model, hence differentiating between model configuration values and `text-embeddings-router` arguments, what do you think @kozistr?

File: router/src/lib.rs (hunk 2 above)
Comment (alvarobartt) [reply router/src/lib.rs:210]: Same here as above, but feel free to drop your feedback or suggestions on wording too 🤗

**Comment by alvarobartt** [comment]
P.S. The `cargo test` are failing with HTTP 401 Unauthorized which is most likely related to the recently included `HF_TOKEN` required to run EmbeddingGemma tests, but I'll look into that as it's unrelated to the PR per se, apologies for the inconvenience 🤗

File: router/src/lib.rs (hunk 1 above)
Comment (kozistr) [reply router/src/lib.rs]: Giving an actionable item for the user is a great idea and looks good to me, too!

File: router/src/lib.rs (hunk 2 above)
Comment (kozistr) [reply router/src/lib.rs:210]: it looks great to me, too! thanks for your suggestion!

**Review by alvarobartt — APPROVED** [review]

File: router/src/lib.rs [hunk 3]
```diff
@@ -184,13 +184,35 @@ pub async fn run(
...
         Some(config) => config.max_seq_length,
         None => {
             tracing::warn!("Could not find a Sentence Transformers config");
             config.max_position_embeddings - position_offset
         }
     };
+
+    // Raise an error when max_input_length is bigger than max_batch tokens to prevent an infinite loop in the queue
+    let max_input_length = if base_input_length > max_batch_tokens {
+        if !auto_truncate {
```
Comment (michaelfeil) [inline router/src/lib.rs:198]: I just removed this baiL!
